Update continue-on-error.yaml

diff --git a/.github/workflows/continue-on-error.yaml b/.github/workflows/continue-on-error.yaml
--- a/.github/workflows/continue-on-error.yaml
+++ b/.github/workflows/continue-on-error.yaml
@@ -1,23 +1,42 @@
-name: working on error or not
+name: error
 
 on:
   workflow_dispatch:
-    inputs:
-      continue_on_error:
-        description: 'Continue on error?'
-        required: true
-        default: 'false'
-        # Add any other relevant validation or options as needed
 
 jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
-      - name: Step 1
+      - name: Step 1 - Job 1
         run: echo "Job 1"
-        
-      - name: Step 2 (Continue on Error)
-        run: echo "Job 1 Step 2"
-        if: ${{ github.event.inputs.continue_on_error == 'true' }}
 
-# Rest of the jobs...
+  job2:
+    runs-on: ubuntu-latest
+    needs: job1
+    if: ${{ job.status == 'success' }}
+    steps:
+      - name: Step 1 - Job 2
+        run: echo "Job 2"
+
+  job3:
+    runs-on: ubuntu-latest
+    needs: job2
+    if: ${{ job.status == 'success' }}
+    steps:
+      - name: Step 1 - Job 3
+        run: echo "Job 3"
+
+  job4:
+    runs-on: ubuntu-latest
+    needs: job3
+    if: ${{ job.status == 'success' }}
+    steps:
+      - name: Step 1 - Job 4 (Intentional Failure)
+        run: exit 1  # Intentionally exit with a non-zero code to indicate failure
+
+  job5:
+    runs-on: ubuntu-latest
+    needs: job4
+    steps:
+      - name: Step 1 - Job 5
+        run: echo "Job 5"
